###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"krishna",
    "username":"krish",
    "password": "krish@456",
    "gender": "Male",
    "location":"hyderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"krish",
    "password": "krish@456"
}